Day01

In [5]:
import numpy as np 
np.__version__

'2.4.6'

In [6]:
l=[1,2,3]
print(type(l))
print(l)
# now we are convert the list into the array
a=np.array(l)
print(type(a))
print(a)

<class 'list'>
[1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3]


In [14]:
a3=np.array([True,False])
print(a3.dtype) #bool
print(a3)

a4=np.array([True,False,10])
print(a4.dtype) # int
print(a4)

a5=np.array([True,10,20.5])
print(a5.dtype) # float
print(a5)

a6=np.array([True,10,10+3j])
print(a6.dtype) # Complext
print(a6)

a7=np.array([10,20,30,"Hi"])
print(a7.dtype) # str
print(a7)

a8=np.array([10,20,{"hello bahi",10,30}])
print(a8.dtype) # object
print(a8)

a9=np.array([10,20,{"age":20,"Name":22}])
print(a9.dtype) #object
print(a9)

bool
[ True False]
int64
[ 1  0 10]
float64
[ 1.  10.  20.5]
complex128
[ 1.+0.j 10.+0.j 10.+3.j]
<U21
['10' '20' '30' 'Hi']
object
[10 20 {'hello bahi', 10, 30}]
object
[10 20 {'age': 20, 'Name': 22}]


##                                                                                    Types of array

## 1 - Dimension Array

In [22]:
a10=np.array([1,2,3,4,5])
a10

array([1, 2, 3, 4, 5])

## 2 - Dimension Array

In [23]:
a12=np.array([[1,2,3],[4,5,6],[7,8,9]])
a12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3 - Dimension Array

In [25]:
a13=np.array([[[1,2,3,],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
a13

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])