Day01

In [8]:
import numpy as np 
np.__version__

'2.4.2'

In [2]:
l=[1,2,3]
print(type(l))
print(l)
# now we are convert the list into the array
a=np.array(l)
print(type(a))
print(a)

<class 'list'>
[1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3]


In [3]:
a3=np.array([True,False])
print(a3.dtype) #bool
print(a3)

a4=np.array([True,False,10])
print(a4.dtype) # int
print(a4)

a5=np.array([True,10,20.5])
print(a5.dtype) # float
print(a5)

a6=np.array([True,10,10+3j])
print(a6.dtype) # Complext
print(a6)

a7=np.array([10,20,30,"Hi"])
print(a7.dtype) # str
print(a7)

a8=np.array([10,20,{"hello bahi",10,30}])
print(a8.dtype) # object
print(a8)

a9=np.array([10,20,{"age":20,"Name":22}])
print(a9.dtype) #object
print(a9)

bool
[ True False]
int64
[ 1  0 10]
float64
[ 1.  10.  20.5]
complex128
[ 1.+0.j 10.+0.j 10.+3.j]
<U21
['10' '20' '30' 'Hi']
object
[10 20 {'hello bahi', 10, 30}]
object
[10 20 {'age': 20, 'Name': 22}]


##                                                                                    Types of array

## 1 - Dimension Array

In [4]:
a10=np.array([1,2,3,4,5])
a10

array([1, 2, 3, 4, 5])

## 2 - Dimension Array

In [5]:
a12=np.array([[1,2,3],[4,5,6],[7,8,9]])
a12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3 - Dimension Array

In [6]:
a13=np.array([[[1,2,3,],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
a13

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

## ndmi


This one is used to find the dimension of the array 

In [16]:
# Example for ther ndim
a111=np.array([1,2,3])
print(a111.ndim) # this will show the current dimension of the a111 array

a122=np.array([[1,2,3],[4,5,6]])
print(a122.ndim) # this will show the current dimension of the a122 array

a133=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(a133.ndim) # this will show the current dimension of the a133 array

1
2
3


## Shapes 


the shape is used to  find the shape  of  the matrix or array

In [21]:
# Examples for the shapes

a143=np.array([1,2,3])
print(a143.shape)

a144=np.array([[1,2,3],[1,2,4]])
print(a144.shape)

a145=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a145.shape)

(3,)
(2, 3)
(1, 3, 3)


## Reshape

the reshape  is used to change the size of the matrix or array which is already created 

In [29]:
# In this example i just made the 2-D array as 2,3 first and then change into the (3,2)

a155=np.array([[1,2,3],[4,5,6]])
print(a155.shape)
print(a155)
a155=a155.reshape(3,2)
print(a155.shape)
print(a155)

(2, 3)
[[1 2 3]
 [4 5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


# Example for the 3-D array 

###
 For the 3-D array we have to use one thing to make  sure we can make the product of (slice , row , column ) are also eqaul to the product of after reshape (slice , row , column)

In [ ]:

# in this state i just created the one 3 - D array in the shape of (2,2,3)
a166=np.array([[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]])
print(a166.shape)
print(a166)


# this one is the reshape part and if you can see that i just reshape the (2,2,3) into the (1,2,6)
a166=a166.reshape(1,2,6)
print(a166.shape)
print(a166)

(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[6 5 4]
  [3 2 1]]]
(1, 2, 6)
[[[1 2 3 4 5 6]
  [6 5 4 3 2 1]]]


## flatlen ()

### the flatlen is  used to convert the mulit dimension array into the uni-dimension array

In [37]:
a166=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(a166.shape)

a166=a166.flatten()
print(a166)

(3, 3, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
